-- 기존 최종 DB를 쿠폰 방식에서 이벤트 자동 할인 방식으로 전환

ALTER TABLE SALON_EVENT ADD (
    TARGET_CATEGORY VARCHAR2(20) DEFAULT 'ALL' NOT NULL,
    DISCOUNT_TYPE VARCHAR2(20),
    DISCOUNT_VALUE NUMBER(12,2),
    MIN_PAYMENT_AMOUNT NUMBER(12) DEFAULT 0 NOT NULL,
    MAX_DISCOUNT_AMOUNT NUMBER(12)
);

-- 기존 이벤트는 할인 조건이 없으므로 안전하게 숨김 처리합니다.
-- 관리자 이벤트 수정 화면에서 할인 조건을 입력한 뒤 다시 노출하세요.
UPDATE SALON_EVENT SET USE_YN='N' WHERE DISCOUNT_TYPE IS NULL OR DISCOUNT_VALUE IS NULL;
ALTER TABLE SALON_EVENT ADD CONSTRAINT SALON_EVENT_TARGET_CATEGORY_CK CHECK (TARGET_CATEGORY IN ('ALL','CUT','PERM','COLOR','CLINIC','ETC'));
ALTER TABLE SALON_EVENT ADD CONSTRAINT SALON_EVENT_DISCOUNT_TYPE_CK CHECK (DISCOUNT_TYPE IS NULL OR DISCOUNT_TYPE IN ('RATE','AMOUNT'));
ALTER TABLE SALON_EVENT ADD CONSTRAINT SALON_EVENT_DISCOUNT_VALUE_CK CHECK (DISCOUNT_VALUE IS NULL OR DISCOUNT_VALUE > 0);
ALTER TABLE SALON_EVENT ADD CONSTRAINT SALON_EVENT_RATE_CK CHECK (DISCOUNT_TYPE IS NULL OR DISCOUNT_TYPE <> 'RATE' OR DISCOUNT_VALUE <= 100);
ALTER TABLE SALON_EVENT ADD CONSTRAINT SALON_EVENT_MIN_PAYMENT_CK CHECK (MIN_PAYMENT_AMOUNT >= 0);
ALTER TABLE SALON_EVENT ADD CONSTRAINT SALON_EVENT_MAX_DISCOUNT_CK CHECK (MAX_DISCOUNT_AMOUNT IS NULL OR MAX_DISCOUNT_AMOUNT >= 0);

ALTER TABLE RESERVATION ADD (
    ORIGINAL_PRICE_SNAPSHOT NUMBER(12),
    EVENT_NO_SNAPSHOT NUMBER,
    EVENT_TITLE_SNAPSHOT VARCHAR2(200),
    DISCOUNT_AMOUNT_SNAPSHOT NUMBER(12) DEFAULT 0,
    FINAL_PRICE_SNAPSHOT NUMBER(12)
);
UPDATE RESERVATION R SET
    ORIGINAL_PRICE_SNAPSHOT=(SELECT S.PRICE FROM SERVICE_MENU S WHERE S.NO=R.SERVICE_MENU_NO),
    DISCOUNT_AMOUNT_SNAPSHOT=0,
    FINAL_PRICE_SNAPSHOT=(SELECT S.PRICE FROM SERVICE_MENU S WHERE S.NO=R.SERVICE_MENU_NO)
WHERE ORIGINAL_PRICE_SNAPSHOT IS NULL;
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_PRICE_CK CHECK (
    ORIGINAL_PRICE_SNAPSHOT IS NULL OR (
        ORIGINAL_PRICE_SNAPSHOT >= 0
        AND DISCOUNT_AMOUNT_SNAPSHOT >= 0
        AND DISCOUNT_AMOUNT_SNAPSHOT <= ORIGINAL_PRICE_SNAPSHOT
        AND FINAL_PRICE_SNAPSHOT = ORIGINAL_PRICE_SNAPSHOT - DISCOUNT_AMOUNT_SNAPSHOT
    )
);

ALTER TABLE PAYMENT DROP CONSTRAINT PAYMENT_MEMBER_COUPON_FK;
ALTER TABLE PAYMENT DROP CONSTRAINT PAYMENT_MEMBER_COUPON_UK;
ALTER TABLE PAYMENT DROP COLUMN MEMBER_COUPON_NO;
ALTER TABLE PAYMENT ADD (EVENT_NO NUMBER, EVENT_TITLE_SNAPSHOT VARCHAR2(200));
ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_EVENT_FK FOREIGN KEY (EVENT_NO) REFERENCES SALON_EVENT(EVENT_NO);

DROP TABLE MEMBER_COUPON CASCADE CONSTRAINTS PURGE;
DROP TABLE COUPON CASCADE CONSTRAINTS PURGE;

CREATE INDEX IDX_SALON_EVENT_DISCOUNT ON SALON_EVENT(USE_YN, TARGET_CATEGORY, START_DATE, END_DATE);
CREATE INDEX IDX_PAYMENT_EVENT ON PAYMENT(EVENT_NO);
COMMIT;
