-- =====================================================================
-- V009__create_site_setting.sql
-- SITE_SETTING 사용자 메인 화면 관리용 설정 테이블 생성
--
-- 관리자 페이지(/admin/siteadmin)에서 수정한
-- 메인 문구, 영역 노출 여부 등의 설정값을 저장한다.
--
-- 저장된 설정값은 사용자 메인 화면(/)에서 조회하여 반영한다.
--
-- 기존 MEMBER, RESERVATION, MATERIAL 등의 테이블과
-- 직접적인 연관 관계가 없으므로 FK는 사용하지 않는다.
--
-- 이미지 파일 자체를 DB에 저장하지 않고
-- 저장된 이미지의 경로만 HERO_IMAGE_URL에 저장한다.
-- =====================================================================


CREATE TABLE SITE_SETTING (

                              SITE_SETTING_NO    NUMBER         GENERATED BY DEFAULT AS IDENTITY,
                              HERO_TITLE         VARCHAR2(200)  NOT NULL,
                              HERO_DESCRIPTION   VARCHAR2(500),
                              HERO_IMAGE_URL     VARCHAR2(500),
                              SERVICE_VISIBLE    CHAR(1)        DEFAULT 'Y' NOT NULL,
                              SERVICE_TITLE      VARCHAR2(100)  DEFAULT '서비스 안내' NOT NULL,
                              STYLE_VISIBLE      CHAR(1)        DEFAULT 'Y' NOT NULL,
                              STYLE_TITLE        VARCHAR2(100)  DEFAULT '헤어스타일 둘러보기' NOT NULL,
                              STYLE_DESCRIPTION  VARCHAR2(500),
                              UPDATED_AT         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,

                              CONSTRAINT SITE_SETTING_PK
                                  PRIMARY KEY (SITE_SETTING_NO),

                              CONSTRAINT SITE_SETTING_SERVICE_VISIBLE_CK
                                  CHECK (SERVICE_VISIBLE IN ('Y', 'N')),

                              CONSTRAINT SITE_SETTING_STYLE_VISIBLE_CK
                                  CHECK (STYLE_VISIBLE IN ('Y', 'N'))
);

COMMIT;